INSERT INTO GENEROS (gen_nome, gen_icone)
VALUES 
('Conto', 'ícone_contos.png'),
('Clássicos', 'ícone_classicos.png'),
('Novela', 'ícone_novela.png'),
('Fábula', 'ícone_fábula.png'),
('Distopia', 'ícone_distopia.png'),
('Fantasia', 'ícone_fantasia.png'),
('Ficção ', 'ícone_ficcao.png'),
('Horror', 'ícone_horror.png'),
('Mistério e Suspense', 'ícone_misterio_suspense.png'),
('Thriller', 'ícone_thriller.png'),
('Aventura', 'ícone_aventura.png'),
('Realismo Mágico', 'ícone_realismo_magico.png'),
('Filosofia', 'ícone_filosofia.png'),
('Política', 'ícone_politica.png'),
('Sociologia', 'ícone_sociologia.png'),
('Psicologia', 'ícone_psicologia.png'),
('Poesia', 'ícone_poesia.png'),
('Comédia', 'ícone_comedia.png'),
('Dramas', 'ícone_dramas.png'),
('Literatura Infantil', 'ícone_literatura_infantil.png'),
('Literatura Juvenil', 'ícone_literatura_juvenil.png'),
('Fábulas para Crianças', 'ícone_fabulas_para_criancas.png'),
('Contos de Fadas', 'ícone_contos_de_fadas.png'),
('Histórias em Quadrinhos (HQ)', 'ícone_historias_em_quadrinhos.png'),
('Livros de Aventura Juvenil', 'ícone_livros_aventura_juvenil.png'),
('Romance', 'romance.png');